.circleci/config.yml, README.md, build.gradle, gradle.properties, gradle/publishing.gradle, gradle/wrapper/gradle-wrapper.properties
Publish plugin to Gradle Central.
Fixes #5
=> Publishing

appveyor.yml, uploadTestResults.ps1
This enables Windows CI for the project. It is simple to setup
https://www.appveyor.com/docs/
=> Add Configuration for AppVeyor

src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerPlugin.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/AbstractFunctionalSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test-functional/resources/sample-spock-tests/build.gradle, src/test-functional/resources/single-spock-test/build.gradle
=> Hook into any task of type Test

.circleci/config.yml, appveyor.yml, build.gradle, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Use plugin inside the plugin

src/main/groovy/com/adarshr/gradle/testlogger/logger/TestEventLogger.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/AbstractFunctionalSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/ThemeSwitchingSpec.groovy
=> Do not log empty suites

src/test-functional/groovy/com/adarshr/gradle/testlogger/AbstractFunctionalSpec.groovy, src/test-functional/resources/sample-junit4-tests/build.gradle, src/test-functional/resources/sample-spock-tests/build.gradle, src/test-functional/resources/single-spock-test/build.gradle
=> Fix test instability

.circleci/config.yml, README.md, build.gradle, gradle/coverage.gradle, src/main/groovy/com/adarshr/gradle/testlogger/util/TimeUtils.groovy
=> Perform code coverage analysis

README.md, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestEventLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/renderer/RenderingContext.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/Theme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/AbstractFunctionalSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerOutput.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/ThemeSwitchingSpec.groovy, src/test-functional/resources/test-marker.gradle, src/test/groovy/com/adarshr/gradle/testlogger/renderer/AnsiTextRendererSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Show summary

README.md, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/ThemeSwitchingSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Make mocha theme closer to mocha-spec reporter

src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Erase ahead before writing summary text

src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/ThemeSwitchingSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Erase ahead before writing every line

src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Show duration for failed tests

README.md, appveyor.yml, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerPlugin.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/ConsoleLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestEventLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/Theme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test-functional/resources/single-spock-test/src/test/groovy/com/adarshr/test/SingleSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/logger/ConsoleLoggerSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Display standard streams

src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerPlugin.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/ThemeSwitchingSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/TestLoggerExtensionSpec.groovy
=> Allow overriding of config using system properties

src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/ThemeSwitchingSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Turn off bright yellow in standard theme

.circleci/config.yml
=> Limit max memory available to Gradle for CircleCI builds

src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/ThemeType.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/ThemeTypeSpec.groovy
=> Add test for ThemeType

src/main/groovy/com/adarshr/gradle/testlogger/logger/OutputCollector.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/ParallelTestLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/SequentialTestLogger.groovy, src/test/groovy/com/adarshr/gradle/testlogger/logger/OutputCollectorSpec.groovy
=> Refactor standard stream collectors into OutputCollector abstraction

README.md, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/ParallelTestLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/SequentialTestLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerAdapter.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/Theme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/ParallelExecutionSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test-functional/resources/sample-spock-tests/src/test/groovy/com/adarshr/test/SecondSpec.groovy, src/test-functional/resources/sample-spock-tests/src/test/groovy/com/adarshr/test/ThirdSpec.groovy, src/test-functional/resources/test-marker.gradle, src/test/groovy/com/adarshr/gradle/testlogger/theme/AbstractThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/BaseThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Filter test results by type

src/main/groovy/com/adarshr/gradle/testlogger/TestDescriptorWrapper.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestResultWrapper.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/OutputCollector.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/ParallelTestLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/SequentialTestLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerAdapter.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/Theme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/util/RendererUtils.groovy, src/test/groovy/com/adarshr/gradle/testlogger/TestDescriptorWrapperSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/TestLoggerExtensionSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/TestResultWrapperSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/logger/OutputCollectorSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/AbstractThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/BaseThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/util/RendererUtilsSpec.groovy
=> Encapsulate core classes

build.gradle, settings.gradle
=> Resolve Gradle deprecation warnings

README.md, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestResultWrapper.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/ParallelExecutionSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/TestLoggerExtensionSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/TestResultWrapperSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/AbstractThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/BaseThemeSpec.groovy
=> Filter standard streams

src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerPlugin.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerWrapper.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/TestLoggerPluginSpec.groovy, src/test-functional/resources/sample-testng-tests/build.gradle, src/test-functional/resources/sample-testng-tests/src/test/java/com/adarshr/test/FirstTest.java, src/test-functional/resources/sample-testng-tests/src/test/java/com/adarshr/test/SecondTest.java, src/test/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerWrapperSpec.groovy
=> Add TestNG based tests

.circleci/config.yml, README.md, appveyor.yml, build.gradle, gradle/coverage.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerPlugin.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/ParallelTestLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/SequentialTestLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerAdapter.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerWrapper.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/AbstractFunctionalSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/ParallelExecutionSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/TestLoggerOutput.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/TestLoggerPluginSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/ThemeSwitchingSpec.groovy, src/test-functional/resources/test-marker.gradle, src/test/groovy/com/adarshr/gradle/testlogger/TestLoggerExtensionSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerWrapperSpec.groovy
- Add ability to configure testlogger for each task
- Move functional tests to dedicated package
- Create a separate task to run functional tests
- Document the new feature
- Mocify CI build scripts to run build instead of test
- Fixes #90
=> Configure testlogger for each task

README.md
=> Clarify documentation about junit-platform Gradle plugin

README.md
=> Highlight lowercase extension name in documentation

build.gradle, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerPlugin.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/ConsoleLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerWrapper.groovy, src/main/groovy/com/adarshr/gradle/testlogger/renderer/AnsiTextRenderer.groovy, src/main/groovy/com/adarshr/gradle/testlogger/renderer/CharHandlers.groovy, src/main/groovy/com/adarshr/gradle/testlogger/renderer/RenderingContext.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/ThemeFactory.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/ThemeType.groovy, src/main/groovy/com/adarshr/gradle/testlogger/util/RendererUtils.groovy, src/test/groovy/com/adarshr/gradle/testlogger/logger/ConsoleLoggerSpec.groovy
=> Add @CompileStatic to all classes

src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/util/RendererUtils.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/BaseThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/util/RendererUtilsSpec.groovy
=> Fix double escaping of brackets

src/main/groovy/com/adarshr/gradle/testlogger/TestResultWrapper.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/AbstractFunctionalSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/TestLoggerPluginSpec.groovy, src/test-functional/resources/sample-spock-tests-system-exit/build.gradle, src/test-functional/resources/sample-spock-tests-system-exit/src/test/groovy/com/adarshr/test/FirstSpec.groovy, src/test-functional/resources/sample-spock-tests-system-exit/src/test/groovy/com/adarshr/test/SecondSpec.groovy, src/test-functional/resources/test-marker.gradle, src/test/groovy/com/adarshr/gradle/testlogger/TestResultWrapperSpec.groovy
=> Show output from before System.exit(5) was called

src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/AbstractFunctionalSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/ParallelExecutionSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/TestLoggerPluginSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/ThemeSwitchingSpec.groovy
Improve Windows build stability
=> Improve Windows build stability

README.md, src/main/groovy/com/adarshr/gradle/testlogger/TestDescriptorWrapper.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/TestLoggerPluginSpec.groovy, src/test-functional/resources/sample-junit5-jupiter-deep-nested-tests/src/test/java/com/adarshr/test/DeepNestedTest.java, src/test/groovy/com/adarshr/gradle/testlogger/TestDescriptorWrapperSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Use classDisplayName for friendlier suite names

README.md, build.gradle, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/test/groovy/com/adarshr/gradle/testlogger/TestLoggerExtensionSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/AbstractThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy
=> Show full stacktraces

build.gradle, gradle.properties, src/main/groovy/com/adarshr/gradle/testlogger/logger/ConsoleLogger.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/AbstractTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/MochaTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/PlainTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/StandardTheme.groovy, src/main/groovy/com/adarshr/gradle/testlogger/util/RendererUtils.groovy, src/test/groovy/com/adarshr/gradle/testlogger/logger/ConsoleLoggerSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/MochaThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/PlainThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardParallelThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/StandardThemeSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/util/RendererUtilsSpec.groovy
=> Ignore tag like expressions in standard streams

build.gradle, src/test-functional/resources/many-spock-tests/build.gradle, src/test-functional/resources/sample-junit5-jupiter-deep-nested-tests/build.gradle, src/test-functional/resources/sample-junit5-jupiter-nested-tests/build.gradle, src/test-functional/resources/sample-junit5-jupiter-tests/build.gradle, src/test-functional/resources/sample-junit5-vintage-tests/build.gradle, src/test-functional/resources/sample-spock-tests-system-exit/build.gradle, src/test-functional/resources/sample-spock-tests/build.gradle, src/test-functional/resources/sample-testng-tests/build.gradle, src/test-functional/resources/single-spock-test/build.gradle, src/test-functional/resources/slow-spock-test/build.gradle
=> Upgrade all dependency versions

src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/test/groovy/com/adarshr/gradle/testlogger/TestLoggerExtensionSpec.groovy
=> Fix issue with overriding logLevel

settings.gradle, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerPlugin.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerAdapter.groovy, src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerWrapper.groovy, src/main/groovy/com/adarshr/gradle/testlogger/theme/ThemeFactory.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/AbstractFunctionalSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/TestLoggerPluginSpec.groovy, src/test-functional/resources/many-spock-tests/build.gradle, src/test-functional/resources/sample-junit4-tests/build.gradle, src/test-functional/resources/sample-junit5-jupiter-deep-nested-tests/build.gradle, src/test-functional/resources/sample-junit5-jupiter-nested-tests/build.gradle, src/test-functional/resources/sample-junit5-jupiter-tests/build.gradle, src/test-functional/resources/sample-junit5-vintage-tests/build.gradle, src/test-functional/resources/sample-spock-tests-system-exit/build.gradle, src/test-functional/resources/sample-spock-tests/build.gradle, src/test-functional/resources/sample-testng-tests/build.gradle, src/test-functional/resources/single-spock-test/build.gradle, src/test-functional/resources/slow-spock-test/build.gradle, src/test-functional/resources/test-marker.gradle, src/test/groovy/com/adarshr/gradle/testlogger/TestLoggerExtensionSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerWrapperSpec.groovy, src/test/groovy/com/adarshr/gradle/testlogger/theme/ThemeFactorySpec.groovy
=> Use lazy configuration

gradle/wrapper/gradle-wrapper.properties, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/AbstractFunctionalSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/ThemeSwitchingSpec.groovy
=> Upgrade to Gradle 6.7

src/main/groovy/com/adarshr/gradle/testlogger/TestDescriptorWrapper.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy, src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtensionProperties.groovy
=> Document extension properties

src/main/groovy/com/adarshr/gradle/testlogger/logger/TestLoggerAdapter.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/ParallelExecutionSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/TestLoggerPluginSpec.groovy, src/test-functional/groovy/com/adarshr/gradle/testlogger/functional/ThemeSwitchingSpec.groovy
=> Fix OutOfMemoryError due to output collector

build.gradle, gradle/publishing.gradle
Upgrade to plugin publish 1.0.0
=> Upgrade to plugin publish 1.0.0
